In [1918]:
import pandas as pd
dataset = pd.read_csv('data/MultipleLinearRegressionData.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


In [1919]:
X, y

(array([[0.5, 4, 'Home'],
        [1.4, 5, 'Library'],
        [2.0, 1, 'Cafe'],
        [2.4, 1, 'Cafe'],
        [2.6, 3, 'Home'],
        [3.2, 1, 'Home'],
        [3.5, 2, 'Home'],
        [3.7, 2, 'Library'],
        [4.5, 3, 'Library'],
        [4.8, 5, 'Home'],
        [5.0, 1, 'Cafe'],
        [5.5, 2, 'Cafe'],
        [5.6, 1, 'Cafe'],
        [6.0, 2, 'Library'],
        [6.5, 2, 'Cafe'],
        [6.3, 1, 'Library'],
        [6.6, 4, 'Home'],
        [7.1, 1, 'Cafe'],
        [8.4, 3, 'Home'],
        [8.6, 3, 'Library'],
        [10.0, 3, 'Library'],
        [0.5, 2, 'Home'],
        [1.2, 3, 'Library'],
        [1.8, 1, 'Cafe'],
        [2.4, 1, 'Cafe'],
        [2.6, 2, 'Home'],
        [3.2, 0, 'Home'],
        [3.9, 0, 'Library'],
        [4.4, 0, 'Library'],
        [4.5, 4, 'Home'],
        [5.0, 1, 'Cafe'],
        [5.3, 1, 'Cafe'],
        [5.8, 0, 'Cafe'],
        [6.0, 2, 'Library'],
        [6.1, 0, 'Cafe'],
        [6.2, 0, 'Library'],
        [6.9, 3, 'Home'],
 

In [1920]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[
 ('encoder', OneHotEncoder(drop='first'), [2])], remainder='passthrough')
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.5, 4],
       [0.0, 1.0, 1.4, 5],
       [0.0, 0.0, 2.0, 1],
       [0.0, 0.0, 2.4, 1],
       [1.0, 0.0, 2.6, 3],
       [1.0, 0.0, 3.2, 1],
       [1.0, 0.0, 3.5, 2],
       [0.0, 1.0, 3.7, 2],
       [0.0, 1.0, 4.5, 3],
       [1.0, 0.0, 4.8, 5],
       [0.0, 0.0, 5.0, 1],
       [0.0, 0.0, 5.5, 2],
       [0.0, 0.0, 5.6, 1],
       [0.0, 1.0, 6.0, 2],
       [0.0, 0.0, 6.5, 2],
       [0.0, 1.0, 6.3, 1],
       [1.0, 0.0, 6.6, 4],
       [0.0, 0.0, 7.1, 1],
       [1.0, 0.0, 8.4, 3],
       [0.0, 1.0, 8.6, 3],
       [0.0, 1.0, 10.0, 3],
       [1.0, 0.0, 0.5, 2],
       [0.0, 1.0, 1.2, 3],
       [0.0, 0.0, 1.8, 1],
       [0.0, 0.0, 2.4, 1],
       [1.0, 0.0, 2.6, 2],
       [1.0, 0.0, 3.2, 0],
       [0.0, 1.0, 3.9, 0],
       [0.0, 1.0, 4.4, 0],
       [1.0, 0.0, 4.5, 4],
       [0.0, 0.0, 5.0, 1],
       [0.0, 0.0, 5.3, 1],
       [0.0, 0.0, 5.8, 0],
       [0.0, 1.0, 6.0, 2],
       [0.0, 0.0, 6.1, 0],
       [0.0, 1.0, 6.2, 0],
       [1.0, 0.0, 6.9, 3],


In [1921]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [1922]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)


LinearRegression()

In [1923]:
y_pred = reg.predict(X_test)
X_test, y_pred, y_test


(array([[0.0, 0.0, 2.4, 1],
        [0.0, 0.0, 7.1, 1],
        [0.0, 0.0, 6.1, 0],
        [1.0, 0.0, 4.5, 4],
        [0.0, 1.0, 10.0, 0],
        [0.0, 0.0, 5.6, 1],
        [1.0, 0.0, 6.9, 3],
        [0.0, 1.0, 10.5, 2],
        [0.0, 1.0, 8.6, 3],
        [0.0, 0.0, 1.8, 1],
        [1.0, 0.0, 2.6, 2],
        [1.0, 0.0, 6.6, 4],
        [0.0, 1.0, 1.4, 5]], dtype=object),
 array([ 23.33141709,  70.21138674,  63.2304313 ,  42.46701167,
        103.19251379,  55.2496943 ,  69.39922576, 102.19273222,
         80.24774894,  17.34674012,  29.50254696,  63.41338109,
          2.44461285]),
 array([ 26,  76,  35,  70, 100,  72,  68,  96,  85,  15,  33,  48,   8]))

In [1924]:
y_test

array([ 26,  76,  35,  70, 100,  72,  68,  96,  85,  15,  33,  48,   8])

In [1925]:
reg.coef_


array([ 7.16974373,  1.06168214,  9.97446163, -2.99350619])

In [1926]:
reg.intercept_


np.float64(2.3862153758322435)

In [1927]:
reg.score(X_train, y_train)

0.8334769058877729

In [1928]:
reg.score(X_test, y_test)


0.8020079428790805

In [1929]:
reg.predict([[0, 0, 9, 1]])


array([89.16286383])

In [1930]:
reg.predict([[0, 0, 9, 0]])

array([92.15637002])

In [1931]:
reg.predict([[1, 0, 9, 0]])

array([99.32611375])

In [1932]:
reg.predict([[0, 1, 9, 0]])

array([93.21805216])